name: portfolio_metrics
version: "0.1.0"
profile: portfolio

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  portfolio_metrics:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

